### ISSUE TITLE
ImportError: /xxx/anaconda3/envs/braille_rl/lib/python3.7/site-packages/v4l2capture.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyString_AS_STRING

### ISSUE THREAD

**Issue by KindleKin** [ac-93/braille_RL#2]
When I run "python algos/dd_dqn_algo/train_discrete_model.py", I got this error.
I have install all pkgs mentioned in guide.md
But I just changed something when I installed python3-v4l2capture.
I just erased the ', libraries = ["v4l2"]' and in setup.py and '#define USE_LIBV4L' in v4l2capture.c, because I got  fatal error: libv4l2.h: No such file or directory when I installed python3-v4l2capture..
Does it trigger this trouble?

**Comment by ac-93** [comment]
Hi,

The v4l2 package should only be necessary if you are using a physical robot with a tactile sensor. I've just altered the code to avoid importing this when using training in simulation.

If you only plan on using the simulation then you should now be able to avoid installing "cri", "vsp" and "python3-v4l2capture" and still successfully run a training script.

I'm not sure on the specific query of whether modifying things when installing python3-v4l2capture will cause issues but I suspect they will. If you do plan on using things on a physical robot with a tactile sensor then let me know and I'll try to help further.

Cheers,
Alex

**Comment by KindleKin** [comment]
> Hi,
> 
> The v4l2 package should only be necessary if you are using a physical robot with a tactile sensor. I've just altered the code to avoid importing this when using training in simulation.
> 
> If you only plan on using the simulation then you should now be able to avoid installing "cri", "vsp" and "python3-v4l2capture" and still successfully run a training script.
> 
> I'm not sure on the specific query of whether modifying things when installing python3-v4l2capture will cause issues but I suspect they will. If you do plan on using things on a physical robot with a tactile sensor then let me know and I'll try to help further.
> 
> Cheers,
> Alex

Oh, thanks!
It works!
But could I visualized what the agent had learned? Just as model in OpenAI gym.

**Comment by ac-93** [comment]
Using the evaluate model scripts can give you some idea of what the agent has learned. I don't have much planned in terms of visualizing the environment as it was always meant a a tool to help get stuff working on the real robot. Sorry!
